name: CMake CI

# Trigger workflow when merging into the main branch
on:
  push:
    branches:
      - feature/ci-test  # Trigger only when merging a pull request into the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu version as the runner environment

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up the C++ compiler environment
    - name: Setup C++ environment
      run: |
        sudo apt update
        sudo apt install -y gcc
        g++ --version

    # Step 3: Configure and build the project
    - name: Configure and Build
      run: |
        mkdir build           # Create a new directory for the build files
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        cmake --build .       # Build the project using CMake

    # Step 4: Run tests using CTest
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure  # Run all tests and display detailed output if any test fails
